### ISSUE TITLE
Statistics and Machine learning toolbox seems to be needed 

### ISSUE THREAD

**Issue by msdev87** [luigiferiani/multi-DDM#1]
I think that the Statistics and Machine learning toolbox is also needed. Maybe this could be added to the installation instructions? 

https://github.com/luigiferiani/multi-DDM/blob/4f23ba409784ec4a69251fd21900aa04c2266812/README.md?plain=1#L21

**Comment by luigiferiani** [comment]
Thank you! Done :)
